apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: Opaque
data:
  SQL_SERVER: d3p0ZXN0LXNxbHNlcnZlci5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_DATABASE: dXNlcmRi
  SQL_USER: dXNlcmRiYWRtaW4=
  SQL_PASSWORD: V2VsY29tZUAxMjM0NQ==
